name: kernel builder

on: 
  push:
    branches:
      - test-10/main

  workflow_dispatch:
  
env:

 # BOT_API_KEY: ${{ secrets.BOT_TOKEN }}
 # CHAT_ID: ${{ secrets.CHAT_ID }} 
  WorkSpace: WorkSpace
  TZ: Asia/Shanghai
  Author: ${{github.actor}}
  
jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: "Cleanup Environment"
        uses: rokibhasansagar/slimhub_actions@main

      - name: Prepare the environment
        run: |
           sudo apt update
           sudo apt -y upgrade
           sudo apt -y install gperf gcc-multilib gcc-10-multilib g++-multilib g++-10-multilib build-essential libstdc++6 clang zlib1g-dev libpng-dev rsync libssl-dev bison flex aria2 make automake zip wget curl git libc6-dev lib32ncurses5-dev libncurses5-dev libncursesw5-dev libncurses5 libwxgtk3.0-gtk3-dev x11proto-core-dev libx11-dev tree lib32z-dev libgl1-mesa-dev libxml2-utils xsltproc bc ccache lib32readline-dev lib32z1-dev liblz4-tool libncurses5-dev libsdl1.2-dev libxml2 lzop pngcrush schedtool squashfs-tools imagemagick libbz2-dev lzma ncftp qemu-user-static libstdc++-10-dev python
          # sudo apt install android-sdk
          
      - name: Set Swap Space
        uses: pierotofy/set-swap-space@master
        with:
           swap-size-gb: 12
  
  #   steps:
      - uses: actions/checkout@v2
      - name: Building Kernel
      
  #      env:
   #     BOT_API_KEY: ${{ secrets.BOT_TOKEN }}
   #     CHAT_ID: ${{ secrets.CHAT_ID }} 
        
        run: |
             chmod +x sync.sh
             chmod +x build-deps.sh
             bash build-deps.sh
             chmod +x print-vars.sh
             bash print-vars.sh
             chmod +x build.sh
             bash build.sh
             chmod +x upload.sh
             bash upload.sh
        
